---
pipeline:
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - bash scripts/tcp-port-wait.sh postgres 5432
      - bash scripts/run-tests.sh --ci
    when:
      event: [pull_request, push, tag]
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=documents_service
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
      - AWS_STORAGE_BUCKET_NAME=example
      - SECRET_KEY=nothing

  bandit:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install bandit
      - bandit -x tests/ -r -lll .
    when:
      event: [pull_request, push, tag]

  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec-walhall/documents_service
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      branch: [master]
      status: [ success ]

  deploy-docs:
    image: python:${PYTHON_VERSION}
    commands:
      - bash scripts/tcp-port-wait.sh $${DATABASE_HOST} $${DATABASE_PORT}
      - pip install -r requirements/base.txt
      - python manage.py generate_swagger > swagger.json
      - eval "$(ssh-agent -s)"
      - mkdir -p /root/.ssh
      - echo "$${SSH_KEY}\n" > /root/.ssh/id_rsa
      - echo "$${SSH_PUBLIC_KEY}\n" > /root/.ssh/id_rsa.pub
      - ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/id_rsa*
      - ssh-add -k /root/.ssh/id_rsa
      - git config --global user.email "engine@humanitec.com"
      - git config --global user.name "HumanitecBot"
      - git clone git@github.com:Humanitec/docs-site.git
      - mkdir -p docs-site/hugo/content/marketplace/products-module/documents-service/
      - mkdir -p docs-site/api/marketplace/documents-service/
      - cd docs-site/hugo/content/marketplace/products-module/documents-service/
      - cp ../../../../../../README.md _index.md -r
      - cd ../../../../../api/marketplace/documents-service
      - cp ../../../../swagger.json swagger.json -r
      - cd ../../../
      - git add .
      - git diff-index --quiet HEAD || git commit -m "Updated documentation for Products service"
      - git push origin master
    secrets: [NPM_USER, NPM_EMAIL, SSH_KEY, SSH_PUBLIC_KEY]
    when:
      event: [push, tag]
      branch: [master]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      event: [push, tag]
      branch: [master, demo, staging, dev]
      status: [failure]

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=documents_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

matrix:
  PYTHON_VERSION:
    - 3.6