version: "2.1"

services:

  postgres_documents_service:
    container_name: postgres_documents_service
    image: postgres:9.6
    environment:
      POSTGRES_DB: documents_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  documents_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documents_service
    image: documents_service
    volumes:
      - .:/code
      - static-content:/static
    ports:
      - "8080:8080"
    depends_on:
      - postgres_documents_service
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "documents_service"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_documents_service"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      CORS_ORIGIN_WHITELIST: "*"
      JWT_PUBLIC_KEY_RSA_ACTIVITYAPI: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----

  nginx_documents:
    image: nginx:latest
    container_name: nginx_documents
    ports:
    - "8001:8000"
    volumes:
    - .:/code
    - ./docker/etc/nginx:/etc/nginx/conf.d
    - static-content:/static
    depends_on:
    - postgres_documents_service

volumes:
  static-content: